### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by Jubeki** [SEU-NetSI/crazyflie-firmware#6]
While recursive cloning the repo on macOS I get the following error:

```
fatal: remote error: upload-pack: not our ref 0156c6f40ec9556bf46b2d4a947ae3ef872cd1bd
Fetched in submodule path 'vendor/CMSIS', but it did not contain 0156c6f40ec9556bf46b2d4a947ae3ef872cd1bd. Direct fetching of that commit failed.
```

Did I do anything wrong?

**Comment by inf1nityhhd** [comment]
Hi, I just reproduced this error.
I checked the commit history and found that the error was caused by an incorrect submodule dependency commit.
There is no [such commit](https://github.com/ARM-software/CMSIS_5/commit/0156c6f40ec9556bf46b2d4a947ae3ef872cd1bd) in the [CMSIS_5 repository](https://github.com/ARM-software/CMSIS_5) that we are currently depending on, but it appears in the [older version](https://github.com/ARM-software/CMSIS/commit/0156c6f40ec9556bf46b2d4a947ae3ef872cd1bd).
I have now fixed this error and tested it on Linux.
It should work fine now.

**Comment by Jubeki** [comment]
I can confirm that it is working now. Thanks.
